// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ From your android google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRkmpSRyXG9SBcEFRl1mriZzGCSlhXHE',
    appId: '1:149754946577:android:240742349de7d5e0b73db0',
    messagingSenderId: '149754946577',
    projectId: 'xception-solutions',
    storageBucket: 'xception-solutions.firebasestorage.app'
  );

  // ✅ From your iOS GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqLjdZ7PKWt0mXqGkPtAN-i0C_5H_ibdI',
    appId: '1:149754946577:ios:2fc6d599d9824458b73db0',
    messagingSenderId: '149754946577',
    projectId: 'xception-solutions',
    storageBucket: 'xception-solutions.firebasestorage.app',
    iosBundleId: 'com.tektronix.xceptionapp'
  );
}